### ISSUE TITLE
d3d10 d3d11 ?

### ISSUE THREAD

**Issue by hydrasho** [iXit/wine-nine-standalone#112]
hello I would like to know does this project exist in version d3d10 d3d11?  thank <3

**Comment by Faalagorn** [comment]
Sadly no, there was a project for that, but it had no developers taking care of before ultimately being removed from Mesa. The code is still available in Git history.

See https://www.reddit.com/r/wine_gaming/comments/6sr4c6/4_years_ago_d3d1x_a_d3d1011_gallium_state_tracker/

**Comment by axeldavy** [comment]
Nope it doesn't. Best is to use DXVK for these.

**Comment by lorn10** [comment]
Just for the sake of completeness, @hydrasho, @Faalagorn there exist since May (2021) a new **d3d10umd** called (DirectX 10) Gallium state tracker in Mesa. And to make it even more interesting, there will be added in the near future also also a **d3d11umd** called (DirectX 11) Gallium state tracker. Both are contributed by **VMware**. Unfortunately they do not work in Wine because the necessary "**WDDM DDI**" (Windows Display Driver Model?) is currently not implemented in Wine. It looks that they work in this point differently than Gallium Nine.

Whatever, more information can be found here:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=54b8137141a7c89956a51b8aa1e7fb7f7ef10cd7
https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/opengl-vulkan-mesa-gallium3d/1272030-gallium-nine-lands-threaded-context-support-other-improvements?p=1273665#post1273665

And the archived source stuff of the failed d3d1x state tracker is available here:
https://chromium.googlesource.com/chromium/deps/mesa/+/refs/heads/main/src/gallium/state_trackers/d3d1x
