### ISSUE TITLE
Install target does not consider the new wine 6.8+ locations

### ISSUE THREAD

**Issue by evelikov** [iXit/wine-nine-standalone#123]
As you may know with wine 6.8 the lookup location of read/fake binaries was changed. Yet wine-nine still uses the old location.

Can we get this fixed upstream, so that distros don't have to carry it locally - for example see this [Arch bug](https://bugs.archlinux.org/task/70994).

In a gist:
```
$libdir/wine/*so -> $libdir/wine/x86_64-unix/*so
$libdir/wine/fakedlls/* -> $libdir/wine/x86_64-windows/*

$lib32dir/wine/*so -> $lib32dir/wine/i386-unix/*so
$lib32dir/wine/fakedlls/* -> $lib32dir/wine/i386-windows/*
```

**Comment by dhewg** [comment]
Thanks for the heads up!

But from a glance it looks to me like Arch installs its wine-nine package **into** the wine directory, hence it's system wide and wine prefix independent.

What the releases of this repo are providing are binaries for a distinct wine prefix, independent of the used wine version. The bundled install scripts installs to the prefix specific `wine winepath -u 'c:\windows\system32'` directory, so it doesn't touch the system wine directory at all (which is why it works so nicely with winetricks or proton).

I've actually yet to try wine >= 6.8 (debian lacks behind with its wine packages and time for games is next to non-existent), but I'm not sure this actually affects us? You'd have to know those wine internal paths to properly archive the integration Arch does, but I guess/hope not for what we're doing here.

**Comment by evelikov** [comment]
I see your point wrt having wine-nine installed in the prefix itself. Although having it system-wide helps with reducing duplication, especially if you have 10-20 of them ;-)

Either way, I hope this helps.

**Comment by dhewg** [comment]
Yeah, it sure does help with reducing duplicates, but that system wide integration is only something that a distro can/should do properly. And those paths only come into play then... I _think_, let's keep this open, I need to check if this indeed doesn't affect us ;)

**Comment by dhewg** [comment]
Just gave it a quick spin on 6.18, works as expected. Our install script as well as winetricks still work as-is.
So it indeed affects only integration packages like on Arch, not the distro independent releases from here.

But thanks again for the heads up, it could have been a problem!
