### ISSUE TITLE
Why not nvidia?

### ISSUE THREAD

**Issue by codeman101** [iXit/wine-nine-standalone#37]
I read that this project is a fix for graphical glitches on Fable Anniversary but I'm running an nvidia driver. Why doesn't this project support nvidia? I read this project also works with the open-source driver but having to switch to that driver for one game isn't ideal hence my question.

**Comment by axeldavy** [comment]
The projects uses 'gallium' an internal API to the open source driver. Thus the name 'gallium nine'.

This open source driver features also support for NVidia (nouveau). If it is not very good and people prefer the proprietary driver it's mostly because NVidia makes things very hard for nouveau devs (no documentation, firmware signing, etc).
